
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KusumgarDatabaseEntities
{

using System;
    using System.Collections.Generic;
    
public partial class Attachment
{

    public int Attachment_Id { get; set; }

    public int Attachment_Type_Id { get; set; }

    public int Ref_Id { get; set; }

    public bool Is_Active { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public int Ref_Type { get; set; }

    public string Document_Name { get; set; }

}

}
