
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KusumgarDatabaseEntities
{

using System;
    using System.Collections.Generic;
    
public partial class Bank_Details
{

    public int Bank_Details_Id { get; set; }

    public Nullable<int> Supplier_Id { get; set; }

    public Nullable<int> Customer_Id { get; set; }

    public string Bank_Name { get; set; }

    public string Bank_Account_No { get; set; }

    public string Branch_Name { get; set; }

    public string Ifsc_Code { get; set; }

    public string Swift_Code { get; set; }

    public string Rtgs_No { get; set; }

    public string Bank_Address { get; set; }

    public string Bank_Code { get; set; }

    public string Account_Code { get; set; }

    public bool Is_Active { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public string Vat { get; set; }

    public Nullable<int> Currency_Id { get; set; }

    public Nullable<int> Payment_Term_Id { get; set; }

    public string Tax_Excemption_Code { get; set; }

}

}
