//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KusumgarDatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Company_Id { get; set; }
        public string Customer_Name { get; set; }
        public string Company_Email { get; set; }
        public string Head_Office_Address { get; set; }
        public int Head_Office_State { get; set; }
        public string Head_Office_ZipCode { get; set; }
        public int Head_Office_Nation { get; set; }
        public string Head_Office_Landline1 { get; set; }
        public string Head_Office_Landline2 { get; set; }
        public string Head_Office_FaxNo { get; set; }
        public string Company_Turnover { get; set; }
        public bool Public_Private_Sector { get; set; }
        public bool Organised_UnOrganised_Sector { get; set; }
        public int Proprietary_Private_Limited { get; set; }
        public int Progressive_Stable_Turmoil { get; set; }
        public Nullable<System.DateTime> Expiration_Date_Of_Contract { get; set; }
        public int Credit_limit { get; set; }
        public bool Auto_Mail_Delivery { get; set; }
        public int Order_Minimum_Value { get; set; }
        public int Order_Maximum_Value { get; set; }
        public bool Is_Approved_By_Director { get; set; }
        public bool Block_Order { get; set; }
        public bool Is_Active { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
    }
}
