
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KusumgarDatabaseEntities
{

using System;
    using System.Collections.Generic;
    
public partial class Enquiry
{

    public int Enquiry_Id { get; set; }

    public int Enquiry_Type_Id { get; set; }

    public int Customer_Id { get; set; }

    public int Quality_Id { get; set; }

    public int PPC_Article_Type_Id { get; set; }

    public int Quality_Set_Id { get; set; }

    public bool Is_Active { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public System.DateTime UpdatedOn { get; set; }

    public string Enquiry_No { get; set; }

    public int Enquiry_Status_Id { get; set; }

}

}
