
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KusumgarDatabaseEntities
{

using System;
    using System.Collections.Generic;
    
public partial class M_Attribute_Code
{

    public int Attribute_Code_Id { get; set; }

    public int Attribute_Id { get; set; }

    public string Attribute_Code_Name { get; set; }

    public string Code { get; set; }

    public bool Status { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

}

}
