//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KusumgarDatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Consumable
    {
        public int Consumable_Id { get; set; }
        public int Category_Id { get; set; }
        public int SubCategory_Id { get; set; }
        public string Material_Name { get; set; }
        public string Material_Code { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDtm { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDtm { get; set; }
    }
}
