
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KusumgarDatabaseEntities
{

using System;
    using System.Collections.Generic;
    
public partial class M_Customer_Quality
{

    public int Customer_Quality_Id { get; set; }

    public int Customer_Id { get; set; }

    public int Quality_Id { get; set; }

    public string Customer_Roll_Length { get; set; }

    public string Storage { get; set; }

    public string Transport { get; set; }

    public string Lot_Testing { get; set; }

    public string End_Product_Criteria { get; set; }

    public string Testing_Requirements { get; set; }

    public string Inspection_Requirements { get; set; }

    public string Process_Control { get; set; }

    public int Sample_Id { get; set; }

    public string Special_Care_Details { get; set; }

    public string Special_Requirements_Material_Handling { get; set; }

    public string Special_Requirements_Packaging { get; set; }

    public string Special_Requirements_Defect_Defination { get; set; }

    public string Special_Requirements_Verdicting { get; set; }

    public bool Is_Active { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

}

}
