
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KusumgarDatabaseEntities
{

using System;
    using System.Collections.Generic;
    
public partial class M_G_Article
{

    public int G_Article_Id { get; set; }

    public int Quality_Id { get; set; }

    public int Yarn_Type_Id { get; set; }

    public int Weave_Id { get; set; }

    public int Grey_with_Cms { get; set; }

    public int GSM { get; set; }

    public string Full_Code { get; set; }

    public int Warp_1 { get; set; }

    public int Warp_2 { get; set; }

    public int Warp_3 { get; set; }

    public int Warp_4 { get; set; }

    public int Weft_1 { get; set; }

    public int Weft_2 { get; set; }

    public int Weft_3 { get; set; }

    public int Weft_4 { get; set; }

    public string Reed { get; set; }

    public string Pick { get; set; }

    public string R_S { get; set; }

    public string G_W { get; set; }

    public int Total_Ends { get; set; }

    public decimal Beam_Weight { get; set; }

    public decimal Beam_Roll { get; set; }

    public decimal Weave { get; set; }

    public decimal No_Of_Healds { get; set; }

    public string Drawing_Sequence_Body { get; set; }

    public string Drawing_Sequence_Selvedge { get; set; }

    public int Roll_Size { get; set; }

    public int Warp_Yarn_Vendor { get; set; }

    public int Weft_Yarn_Vendor { get; set; }

    public int RSP { get; set; }

    public int Warping_Meters { get; set; }

    public string Draft { get; set; }

    public int Crimp_In_Percentage { get; set; }

    public int Peg_Plan_Rows { get; set; }

    public int Peg_Plan_Columns { get; set; }

    public bool Is_Active { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

}

}
