
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KusumgarDatabaseEntities
{

using System;
    using System.Collections.Generic;
    
public partial class M_Material_Vendor
{

    public int Material_Vendor_Id { get; set; }

    public int Material_Id { get; set; }

    public int Vendor_Id { get; set; }

    public int Priority_Order { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

}

}
