//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KusumgarDatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_P_Article
    {
        public int P_Article_Id { get; set; }
        public int Quality_No { get; set; }
        public int Yarn_Type_Id { get; set; }
        public int Weave_Id { get; set; }
        public int Shade_Id { get; set; }
        public int Chemical_Finish_Id { get; set; }
        public int Mechanical_Finish_Id { get; set; }
        public decimal P_Finish_width { get; set; }
        public int Type_Id { get; set; }
        public string Full_Code { get; set; }
        public int Given_By_Id { get; set; }
        public int Validated_By_Id { get; set; }
        public int Developed_Under_Id { get; set; }
        public string Batch { get; set; }
        public bool Is_Active { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
