//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KusumgarDatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Product_Vendors
    {
        public int Product_Vendor_Id { get; set; }
        public int Vendor_Id { get; set; }
        public int Product_Type { get; set; }
        public string Name { get; set; }
        public bool Original_Manufacturer { get; set; }
        public bool Is_Active { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public string Inspection_Facility { get; set; }
        public string Testing_Facility { get; set; }
    }
}
