
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KusumgarDatabaseEntities
{

using System;
    using System.Collections.Generic;
    
public partial class M_Quality
{

    public int Quality_Id { get; set; }

    public int Yarn_Type { get; set; }

    public string Reed { get; set; }

    public string Pick { get; set; }

    public int Weave { get; set; }

    public Nullable<int> Minimum_Order_Size { get; set; }

    public Nullable<int> Ideal_Roll_Length { get; set; }

    public Nullable<int> Our_Sample_No { get; set; }

    public Nullable<int> Quality_No { get; set; }

    public bool Status { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int Yarn_Type_Id { get; set; }

}

}
