
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KusumgarDatabaseEntities
{

using System;
    using System.Collections.Generic;
    
public partial class M_SubCategory
{

    public int SubCategoryId { get; set; }

    public int CategoryId { get; set; }

    public string SubCategoryName { get; set; }

    public bool IsActive { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedDate { get; set; }

    public int UpdatedBy { get; set; }

    public System.DateTime UpdatedDate { get; set; }

}

}
