
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KusumgarDatabaseEntities
{

using System;
    using System.Collections.Generic;
    
public partial class M_Test
{

    public int Test_Id { get; set; }

    public int Fabric_Type_Id { get; set; }

    public string Test_Name { get; set; }

    public Nullable<int> Test_Unit1 { get; set; }

    public Nullable<int> Test_Unit2 { get; set; }

    public Nullable<int> Test_Unit3 { get; set; }

    public Nullable<int> Test_Unit4 { get; set; }

    public Nullable<int> Test_Unit5 { get; set; }

    public Nullable<int> Test_Unit6 { get; set; }

    public Nullable<int> Test_Unit7 { get; set; }

    public Nullable<int> Test_Unit8 { get; set; }

    public Nullable<int> Test_Unit9 { get; set; }

    public Nullable<int> Test_Unit10 { get; set; }

    public bool Status { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime UpdatedOn { get; set; }

    public int UpdatedBy { get; set; }

}

}
