//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KusumgarDatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_User
    {
        public int UserId { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Mobile_No1 { get; set; }
        public string Mobile_No2 { get; set; }
        public string Residence_Landline { get; set; }
        public string Office_Landline { get; set; }
        public string Office_Address { get; set; }
        public string Residence_Address { get; set; }
        public string Office_PinCode { get; set; }
        public string Residence_PinCode { get; set; }
        public string Designtation { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string Fax_No { get; set; }
        public System.DateTime Date_Of_Joining { get; set; }
        public string Personal_Email { get; set; }
        public string Office_Email { get; set; }
        public int Gender { get; set; }
        public Nullable<bool> System_User_Flag { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public bool Is_Active { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
    }
}
