//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KusumgarDatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Work_Center
    {
        public int Work_Center_Id { get; set; }
        public Nullable<int> Purpose { get; set; }
        public int Work_Station_Id { get; set; }
        public string Work_Center_Code { get; set; }
        public string Machine_Name { get; set; }
        public string Machine_Properties { get; set; }
        public int TPM_Speed { get; set; }
        public decimal Average_Order_Length { get; set; }
        public string Capacity { get; set; }
        public int Wastage { get; set; }
        public int Target_Efficiency { get; set; }
        public bool Under_Maintainance { get; set; }
        public bool Is_Active { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public int UpdatedBy { get; set; }
    }
}
