
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KusumgarDatabaseEntities
{

using System;
    using System.Collections.Generic;
    
public partial class M_Y_Article
{

    public int Y_Article_Id { get; set; }

    public int Denier_Id { get; set; }

    public int Twist_Mingle_Id { get; set; }

    public int Twist_Type_Id { get; set; }

    public int Ply_Id { get; set; }

    public int Yarn_Type_Id { get; set; }

    public int Shade_Id { get; set; }

    public int Filaments_Id { get; set; }

    public int Origin_Id { get; set; }

    public int Shrinkage_Id { get; set; }

    public int Tenasity_Id { get; set; }

    public int Chemical_Treatment_Id { get; set; }

    public int Colour_Id { get; set; }

    public int Supplier_Id { get; set; }

    public string Full_Code { get; set; }

    public int Given_By_Id { get; set; }

    public int Validated_By_Id { get; set; }

    public int Developed_Under_Id { get; set; }

    public string Lead_Time_To_Purchase { get; set; }

    public int Work_Station_Id { get; set; }

    public bool Is_Active { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public System.DateTime UpdatedOn { get; set; }

}

}
