//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KusumgarDatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staggered_Order
    {
        public int Staggered_Order_Id { get; set; }
        public int Enquiry_Id { get; set; }
        public string Order_No { get; set; }
        public int Order_Status { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Delivery_Date { get; set; }
        public bool Is_Active { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
