
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KusumgarDatabaseEntities
{

using System;
    using System.Collections.Generic;
    
public partial class Supporting_Details
{

    public int Supporting_Details_Id { get; set; }

    public int Enquiry_Id { get; set; }

    public int Rate { get; set; }

    public int Customer_Roll_Length { get; set; }

    public string Packing { get; set; }

    public string Dispatch { get; set; }

    public string Additional_Customer_Prop { get; set; }

    public string Source_Of_Enquiry { get; set; }

    public bool Is_Active { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public System.DateTime UpdatedOn { get; set; }

}

}
