
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KusumgarDatabaseEntities
{

using System;
    using System.Collections.Generic;
    
public partial class System_Default
{

    public int System_Default_Id { get; set; }

    public string System_Default_Name { get; set; }

    public string Value { get; set; }

    public Nullable<int> Created_By { get; set; }

    public Nullable<System.DateTime> Created_Dt { get; set; }

    public Nullable<int> Updated_By { get; set; }

    public Nullable<System.DateTime> Updated_Dt { get; set; }

}

}
