//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KusumgarDatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Customer_Quality_Details
    {
        public Nullable<int> Enquiry_Id { get; set; }
        public string Width_Of_Fabric { get; set; }
        public string Coating { get; set; }
        public string Applications { get; set; }
        public string Physicla_Appearance { get; set; }
        public Nullable<int> Shades { get; set; }
        public string Finish { get; set; }
        public string Prints { get; set; }
        public Nullable<int> Customer_Approved_Sample { get; set; }
        public string Market_Segment { get; set; }
        public string Lable_Tagging { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string Physical_Appearance { get; set; }
        public Nullable<decimal> Wrap_Count { get; set; }
        public Nullable<decimal> Weft_Count { get; set; }
        public Nullable<decimal> Ends_Per_Inch { get; set; }
        public Nullable<decimal> Pick_Per_Inch { get; set; }
    }
}
