
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KusumgarDatabaseEntities
{

using System;
    using System.Collections.Generic;
    
public partial class Temp_Visual_Parameters
{

    public int Temp_Visual_Parameters_Id { get; set; }

    public int Enquiry_Id { get; set; }

    public int Defect_Id { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int UpdatedBy { get; set; }

    public System.DateTime UpdatedOn { get; set; }

}

}
